# Generated by Django 5.0.3 on 2024-05-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=10)),
                ('subject1_marks', models.IntegerField()),
                ('subject2_marks', models.IntegerField()),
                ('subject3_marks', models.IntegerField()),
            ],
        ),
    ]
